### ISSUE TITLE
TypeError: killTor is not a function

### ISSUE THREAD

**Issue by 174n** [prohetamine/tor-speech#1]
```
TypeError: killTor is not a function
    at /mnt/c/Users/ivan/Desktop/tts/tts.js:13:3
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Вот код из примера:

```js
const TorSpeech = require('tor-speech')

;(async () => {
  const { killTor, yandex, langCodes } = await TorSpeech()

  const result = await yandex({
    text: 'Привет, как дела ?',
    langCode: langCodes.russian
  })

  console.log(result)

  killTor()
})()
```

Использую WSL, на винде не ставилось

Еще вот какая ошибка, видимо какой-то либы не хватает, но libevent пакет установлен

```txt
/tmp/Tor/tor: error while loading shared libraries: libevent-2.1.so.7: cannot open shared object file: No such
 file or directory
```

**Comment by prohetamine** [comment]
Доброй ночи, я клонировал репозиторий и установил тор, проверил test.js все
работает, проверил пример из документации и тоже все работает, вероятно
проблема связана с тем что у вас не правильно установлен тор или не
установлен вовсе или что-то с путем, попробуйте передать путь на бинарный
файл в TorSpeech(/* path */)

вс, 15 авг. 2021 г. в 12:49, Ivan Alexandrov ***@***.***>:

**Comment by 174n** [comment]
А, вот оно что. Я просто видел в пакетах tor-downloader, думал он сам скачает. Спасибо за ответ
